version: 2

models:
  - name: dim_products
    description: "Dimension table containing product details."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
      - name: product_name
        description: "Name of the product."
      - name: category
        description: "Category of the product."
      - name: about_product
        description: "Description of the product."
      - name: img_link
        description: "Link to the product image."
      - name: product_link
        description: "Link to the product page."

  - name: dim_users
    description: "Dimension table containing user details."
    columns:
      - name: user_id
        description: "Unique identifier for the user."
      - name: user_name
        description: "Name of the user."

  - name: dim_reviews
    description: "Dimension table containing review details."
    columns:
      - name: review_id
        description: "Unique identifier for the review."
      - name: review_title
        description: "Title of the review."
      - name: review_content
        description: "Content of the review."

  - name: fact_sales
    description: "Fact table containing sales and transaction metrics."
    columns:
      - name: product_id
        description: "Foreign key referencing dim_products."
      - name: user_id
        description: "Foreign key referencing dim_users."
      - name: discounted_price
        description: "Final price after discounts."
      - name: actual_price
        description: "Original price of the product."
      - name: discount_percentage
        description: "Percentage discount applied."
      - name: rating
        description: "Rating given to the product."
      - name: rating_count
        description: "Number of ratings for the product."
      - name: review_id
        description: "Foreign key referencing dim_reviews."

  - name: user_lifetime_spend
    description: "Aggregated table showing total lifetime spend for each user."
    columns:
      - name: user_id
        description: "Unique identifier for the user."
      - name: user_name
        description: "Name of the user."
      - name: total_spend
        description: "Total amount spent by the user in their lifetime."

  - name: category_sales_performance
    description: "Aggregated table showing revenue and average rating for each product category."
    columns:
      - name: category
        description: "Category of the product."
      - name: revenue_generated
        description: "Total revenue generated by products in this category."
      - name: average_rating
        description: "Average customer rating for products in this category."

  - name: user_top_category
    description: "Shows the category that generates the most revenue for each user and the number of orders in that category."
    columns:
      - name: user_id
        description: "Unique identifier for the user."
      - name: top_category
        description: "Category that generated the most revenue for the user."
      - name: total_revenue
        description: "Total revenue generated by the top category for the user."
      - name: order_count
        description: "Number of orders made by the user in the top category."

  - name: stg_amazon_sales_data
    description: "Staging model for amazon sales data. Filters out rows with null values and prepares clean data for downstream transformations."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
      - name: product_name
        description: "Name of the product."
      - name: category
        description: "Product category."
      - name: actual_price
        description: "Actual price of the product."
      - name: user_id
        description: "Unique identifier for the user."